# Generated by Django 4.0.4 on 2022-09-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('product_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
